package controller.hr;

import controller.base.BaseServlet;
import dao.CommonDAO;
import dao.UserDAO;
import model.Department;
import model.RecruitmentProposal;
import model.User;

import java.io.IOException;
import java.util.List;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/hr/create-user")
public class CreateUserServlet extends BaseServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        User currentUser = getCurrentUser(request);
        if (currentUser == null) {
            redirectToLogin(request, response);
            return;
        }

        if (currentUser.getRoleId() != ROLE_HR_MANAGER && currentUser.getRoleId() != ROLE_ADMIN) {
            sendForbidden(request, response, "Bạn không có quyền thực hiện thao tác này!");
            return;
        }

        UserDAO userDAO = new UserDAO();
        CommonDAO commonDAO = new CommonDAO();

        // 1. XỬ LÝ AJAX LẤY CẤU HÌNH THEO ROLE
        String action = request.getParameter("action");
        if ("getRoleConfig".equals(action)) {
            int roleId = getIntParameter(request, "roleId", -1);

            String prefix = getPrefixByRoleId(roleId);
            String nextCode = userDAO.generateNextCode(prefix);

            int defaultDeptId = getDefaultDepartmentIdByRole(roleId, commonDAO);
            int defaultPosId = getDefaultPositionIdByRole(roleId, commonDAO);

            response.setContentType("application/json;charset=UTF-8");
            String json = String.format("{\"code\":\"%s\", \"deptId\":%d, \"posId\":%d}",
                    nextCode, defaultDeptId, defaultPosId);
            response.getWriter().write(json);
            return;
        }

        List<Department> departments = commonDAO.getAllDepartments();

        // 2. KIỂM TRA NẾU ĐƯỢC CHUYỂN HƯỚNG TỪ ĐỀ XUẤT (?proposalId=...)
        int proposalId = getIntParameter(request, "proposalId", -1);
        if (proposalId != -1) {
            RecruitmentProposal proposal = userDAO.getProposalById(proposalId);
            if (proposal != null) {
                // Tự động xác định Department ID dựa trên vị trí đề xuất nếu chưa có
                if (proposal.getDepartmentId() == null || proposal.getDepartmentId() <= 0) {
                    int autoDeptId = resolveDepartmentByPositionTitle(proposal.getPositionTitle(), departments);
                    proposal.setDepartmentId(autoDeptId);
                }
                request.setAttribute("proposal", proposal);
            }
        }

        String defaultCode = userDAO.generateNextCode("NV");

        request.setAttribute("branches", commonDAO.getAllBranches());
        request.setAttribute("departments", departments);
        request.setAttribute("positions", commonDAO.getAllPositions());
        request.setAttribute("roles", commonDAO.getHRManageableRoles());
        request.setAttribute("autoGeneratedCode", defaultCode);

        request.getRequestDispatcher("/WEB-INF/views/hr/create-user.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        User currentUser = getCurrentUser(request);
        if (currentUser == null || (currentUser.getRoleId() != ROLE_HR_MANAGER && currentUser.getRoleId() != ROLE_ADMIN)) {
            sendForbidden(request, response, "Bạn không có quyền thực hiện thao tác này!");
            return;
        }

        int proposalId = getIntParameter(request, "proposalId", -1);
        String username = getStringParameter(request, "username");
        String email = getStringParameter(request, "email");
        int roleId = getIntParameter(request, "roleId", -1);
        String fullName = getStringParameter(request, "fullName");
        String phone = getStringParameter(request, "phone");
        String identityCard = getStringParameter(request, "identityCard");
        int homeBranchId = getIntParameter(request, "homeBranchId", -1);
        int departmentId = getIntParameter(request, "departmentId", -1);
        int positionId = getIntParameter(request, "positionId", -1);
        String employeeType = getStringParameter(request, "employeeType");
        String shiftType = getStringParameter(request, "shiftType");
        String expirationDate = getStringParameter(request, "expirationDate");

        UserDAO userDAO = new UserDAO();

        // VALIDATION ĐẦU VÀO
        if (userDAO.isUsernameExists(username)) {
            request.setAttribute("error", "Mã nhân viên (Username) '" + username + "' đã tồn tại!");
            doGet(request, response);
            return;
        }

        if (email != null && !email.trim().isEmpty() && userDAO.isEmailExists(email)) {
            request.setAttribute("error", "Email '" + email + "' đã được sử dụng!");
            doGet(request, response);
            return;
        }

        if (userDAO.isPhoneExists(phone)) {
            request.setAttribute("error", "Số điện thoại '" + phone + "' đã tồn tại trong hệ thống!");
            doGet(request, response);
            return;
        }

        if (userDAO.isIdentityCardExists(identityCard)) {
            request.setAttribute("error", "Số CCCD/CMND '" + identityCard + "' đã tồn tại!");
            doGet(request, response);
            return;
        }

        // Tạo chuỗi thông tin tài khoản để gửi vào note cho Store Manager
        String noteForStoreManager = String.format("Đã phê duyệt. Tài khoản cấp mới - Username: %s | Mật khẩu mặc định: 123456 (Yêu cầu đổi khi đăng nhập lần đầu)", username);

        // Sửa lại gọi đúng tên hàm có tích hợp tạo hợp đồng
        boolean success = userDAO.createUserWithProfileAndApproveProposalCustomNote(
                username, email, roleId, expirationDate,
                fullName, phone, identityCard, homeBranchId,
                positionId, departmentId, employeeType, shiftType,
                proposalId, currentUser.getId(), noteForStoreManager);

        if (success) {
            // Nếu tạo từ Đề xuất -> Chuyển hướng quay lại danh sách đề xuất tuyển dụng
            if (proposalId > 0) {
                response.sendRedirect(request.getContextPath() + "/hr/recruitment?msg=approved");
                return;
            }
            // Nếu HR tự tạo trực tiếp -> Ở lại trang thông báo thành công
            request.setAttribute("message", "Tạo tài khoản thành công! Mật khẩu mặc định: 123456");
        } else {
            request.setAttribute("error", "Thao tác thất bại! Vui lòng kiểm tra lại kết nối cơ sở dữ liệu.");
        }

        doGet(request, response);
    }

    private String getPrefixByRoleId(int roleId) {
        switch (roleId) {
            case 1:
                return "ADM";
            case 2:
                return "DIR";
            case 3:
                return "HR";
            case 4:
                return "QL";
            default:
                return "NV";
        }
    }

    private int getDefaultDepartmentIdByRole(int roleId, CommonDAO commonDAO) {
        if (roleId == 4) {
            return commonDAO.getAllDepartments().stream()
                    .filter(d -> d.getName().toLowerCase().contains("vận hành"))
                    .mapToInt(Department::getId)
                    .findFirst().orElse(0);
        }
        if (roleId == 3) {
            return commonDAO.getAllDepartments().stream()
                    .filter(d -> d.getName().toLowerCase().contains("nhân sự"))
                    .mapToInt(Department::getId)
                    .findFirst().orElse(0);
        }
        return 0;
    }

    private int getDefaultPositionIdByRole(int roleId, CommonDAO commonDAO) {
        if (roleId == 4) {
            return commonDAO.getAllPositions().stream()
                    .filter(p -> p.getTitle().toLowerCase().contains("quản lý chi nhánh"))
                    .mapToInt(p -> p.getId())
                    .findFirst().orElse(0);
        }
        return 0;
    }

    /**
     * Tự động xác định ID Phòng ban dựa trên Tên vị trí tuyển dụng
     */
    private int resolveDepartmentByPositionTitle(String title, List<Department> departments) {
        if (title == null || title.trim().isEmpty() || departments == null) {
            return 0;
        }

        String lowerTitle = title.toLowerCase();
        boolean isSalesOrCashier = lowerTitle.contains("thu ngân") || lowerTitle.contains("bán hàng") || lowerTitle.contains("trưng bày");

        for (Department dept : departments) {
            String deptNameLower = dept.getName().toLowerCase();
            if (isSalesOrCashier) {
                if (deptNameLower.contains("thu ngân") || deptNameLower.contains("bán hàng")) {
                    return dept.getId();
                }
            } else {
                if (deptNameLower.contains("vận hành")) {
                    return dept.getId();
                }
            }
        }

        return departments.isEmpty() ? 0 : departments.get(0).getId();
    }
}
