package controller.hr;

import controller.base.BaseServlet;
import dao.CommonDAO;
import dao.UserDAO;
import java.io.IOException;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import model.User;

@WebServlet("/hr/create-user")
public class CreateUserServlet extends BaseServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        User currentUser = getCurrentUser(request);
        if (currentUser == null) {
            redirectToLogin(request, response);
            return;
        }

        if (currentUser.getRoleId() != ROLE_HR_MANAGER && currentUser.getRoleId() != ROLE_ADMIN) {
            sendForbidden(request, response, "Bạn không có quyền thực hiện thao tác này!");
            return;
        }

        UserDAO userDAO = new UserDAO();
        CommonDAO commonDAO = new CommonDAO();

        // -----------------------------------------------------------------------
        // XỬ LÝ AJAX LẤY CẤU HÌNH THEO ROLE (CHUẨN MVC - TRẢ VỀ JSON)
        // -----------------------------------------------------------------------
        String action = request.getParameter("action");
        if ("getRoleConfig".equals(action)) {
            int roleId = getIntParameter(request, "roleId", -1);

            String prefix = getPrefixByRoleId(roleId);
            String nextCode = userDAO.generateNextCode(prefix);

            // Tìm ID chuẩn từ Database thông qua commonDAO
            int defaultDeptId = getDefaultDepartmentIdByRole(roleId, commonDAO);
            int defaultPosId = getDefaultPositionIdByRole(roleId, commonDAO);

            response.setContentType("application/json;charset=UTF-8");
            String json = String.format("{\"code\":\"%s\", \"deptId\":%d, \"posId\":%d}",
                    nextCode, defaultDeptId, defaultPosId);
            response.getWriter().write(json);
            return;
        }

        // Mặc định ban đầu khi tải trang
        String defaultCode = userDAO.generateNextCode("NV");

        request.setAttribute("branches", commonDAO.getAllBranches());
        request.setAttribute("departments", commonDAO.getAllDepartments());
        request.setAttribute("positions", commonDAO.getAllPositions());
        request.setAttribute("roles", commonDAO.getHRManageableRoles());
        request.setAttribute("autoGeneratedCode", defaultCode);

        request.getRequestDispatcher("/WEB-INF/views/hr/create-user.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        User currentUser = getCurrentUser(request);
        if (currentUser == null || (currentUser.getRoleId() != ROLE_HR_MANAGER && currentUser.getRoleId() != ROLE_ADMIN)) {
            sendForbidden(request, response, "Bạn không có quyền thực hiện thao tác này!");
            return;
        }

        String username = getStringParameter(request, "username");
        String email = getStringParameter(request, "email");
        int roleId = getIntParameter(request, "roleId", -1);
        String fullName = getStringParameter(request, "fullName");
        String phone = getStringParameter(request, "phone");
        String identityCard = getStringParameter(request, "identityCard");
        int homeBranchId = getIntParameter(request, "homeBranchId", -1);
        int departmentId = getIntParameter(request, "departmentId", -1);
        int positionId = getIntParameter(request, "positionId", -1);
        String employeeType = getStringParameter(request, "employeeType");
        String expirationDate = getStringParameter(request, "expirationDate");

        UserDAO userDAO = new UserDAO();

        // VALIDATION ĐẦU VÀO
        if (userDAO.isUsernameExists(username)) {
            request.setAttribute("error", "Mã nhân viên (Username) '" + username + "' đã tồn tại!");
            doGet(request, response);
            return;
        }

        if (email != null && !email.trim().isEmpty() && userDAO.isEmailExists(email)) {
            request.setAttribute("error", "Email '" + email + "' đã được sử dụng!");
            doGet(request, response);
            return;
        }

        // Bổ sung check trùng Số điện thoại
        if (userDAO.isPhoneExists(phone)) {
            request.setAttribute("error", "Số điện thoại '" + phone + "' đã tồn tại trong hệ thống!");
            doGet(request, response);
            return;
        }

        if (userDAO.isIdentityCardExists(identityCard)) {
            request.setAttribute("error", "Số CCCD/CMND '" + identityCard + "' đã tồn tại!");
            doGet(request, response);
            return;
        }

        boolean success = userDAO.createUserWithProfile(
                username, email, roleId, expirationDate,
                fullName, phone, identityCard, homeBranchId,
                positionId, departmentId, employeeType);

        if (success) {
            request.setAttribute("message", "Tạo tài khoản thành công! Mật khẩu mặc định: 123456");
        } else {
            request.setAttribute("error", "Tạo tài khoản thất bại! Vui lòng kiểm tra lại kết nối cơ sở dữ liệu.");
        }

        doGet(request, response);
    }

    // --- CÁC HÀM XỬ LÝ LOGIC NGHIỆP VỤ NẰM Ở CONTROLLER ---
    private String getPrefixByRoleId(int roleId) {
        switch (roleId) {
            case 1:
                return "ADM";
            case 2:
                return "DIR";
            case 3:
                return "HR";
            case 4:
                return "QL";
            default:
                return "NV";
        }
    }

    private int getDefaultDepartmentIdByRole(int roleId, CommonDAO commonDAO) {
        if (roleId == 4) { // Store Manager
            // Duyệt danh sách Phòng ban từ DB để tìm đúng ID của "Bộ Phận Vận Hành"
            return commonDAO.getAllDepartments().stream()
                    .filter(d -> d.getName().toLowerCase().contains("vận hành"))
                    .mapToInt(d -> d.getId())
                    .findFirst().orElse(0);
        }
        if (roleId == 3) { // HR
            return commonDAO.getAllDepartments().stream()
                    .filter(d -> d.getName().toLowerCase().contains("nhân sự"))
                    .mapToInt(d -> d.getId())
                    .findFirst().orElse(0);
        }
        return 0;
    }

    private int getDefaultPositionIdByRole(int roleId, CommonDAO commonDAO) {
        if (roleId == 4) { // Store Manager
            // Duyệt danh sách Vị trí từ DB để tìm đúng ID của "Quản Lý Chi Nhánh"
            return commonDAO.getAllPositions().stream()
                    .filter(p -> p.getTitle().toLowerCase().contains("quản lý chi nhánh"))
                    .mapToInt(p -> p.getId())
                    .findFirst().orElse(0);
        }
        return 0;
    }
}
