<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html>
<html lang="vi">
    <head>
        <meta charset="UTF-8">
        <title>Cấp Tài Khoản Nhân Sự Từ Đề Xuất</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {
                background-color: #f8f9fa;
            }
            .card-custom {
                max-width: 850px;
                margin: 30px auto;
                border-radius: 12px;
                box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            }
            .section-title {
                font-size: 16px;
                font-weight: 600;
                color: #0d6efd;
                margin-bottom: 15px;
                border-bottom: 2px solid #e9ecef;
                padding-bottom: 5px;
            }
        </style>
    </head>
    <body>

        <div class="container">
            <div class="card card-custom p-4 bg-white">
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <h3 class="mb-0 text-primary">Cấp Tài Khoản Nhân Sự Mới</h3>
                    <a href="${pageContext.request.contextPath}/hr/recruitment" class="btn btn-outline-secondary btn-sm">Quay lại danh sách đề xuất</a>
                </div>

                <c:if test="${not empty message}">
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        ${message}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                </c:if>

                <c:if test="${not empty error}">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        ${error}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                </c:if>

                <form action="${pageContext.request.contextPath}/hr/create-user" method="post">
                    
                    <!-- Dữ liệu ẩn liên kết với Đề xuất -->
                    <c:if test="${not empty proposal}">
                        <input type="hidden" name="proposalId" value="${proposal.id}">
                    </c:if>

                    <!-- 1. THÔNG TIN TÀI KHOẢN -->
                    <div class="section-title">1. Thông tin tài khoản & Đăng nhập</div>
                    <div class="row g-3 mb-3">
                        <div class="col-md-4">
                            <label class="form-label font-semibold">Mã nhân viên (Username) <span class="text-danger">*</span></label>
                            <input type="text" id="usernameInput" name="username" value="${autoGeneratedCode}" class="form-control" readonly style="background-color: #e9ecef;" required>
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Email</label>
                            <input type="email" name="email" value="${not empty proposal && not empty proposal.candidate ? proposal.candidate.email : ''}" class="form-control" placeholder="nguyenvana@gmail.com">
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Vai trò (Role) <span class="text-danger">*</span></label>
                            <select id="roleSelect" name="roleId" class="form-select" required>
                                <c:forEach var="r" items="${roles}">
                                    <option value="${r.id}" ${r.id == 5 ? 'selected' : ''}>${r.name} (${r.description})</option>
                                </c:forEach>
                            </select>
                        </div>
                    </div>

                    <!-- 2. THÔNG TIN CÁ NHÂN -->
                    <div class="section-title">2. Thông tin cá nhân ứng viên</div>
                    <div class="row g-3 mb-3">
                        <div class="col-md-5">
                            <label class="form-label">Họ và tên <span class="text-danger">*</span></label>
                            <input type="text" name="fullName" value="${not empty proposal && not empty proposal.candidate ? proposal.candidate.fullName : ''}" class="form-control" placeholder="Nguyễn Văn A" required>
                        </div>
                        <div class="col-md-3">
                            <label class="form-label">Số điện thoại <span class="text-danger">*</span></label>
                            <input type="text" name="phone" value="${not empty proposal && not empty proposal.candidate ? proposal.candidate.phone : ''}" class="form-control" placeholder="090XXXXXXX" required>
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Số CCCD/CMND <span class="text-danger">*</span></label>
                            <input type="text" name="identityCard" value="${not empty proposal && not empty proposal.candidate ? proposal.candidate.identityCard : ''}" class="form-control" placeholder="001090XXXXXX" required>
                        </div>
                    </div>

                    <!-- 3. PHÂN CÔNG TỔ CHỨC -->
                    <div class="section-title">3. Phân công tổ chức</div>
                    <div class="row g-3 mb-3">
                        <div class="col-md-4">
                            <label class="form-label">Cơ sở làm việc <span class="text-danger">*</span></label>
                            <select name="homeBranchId" class="form-select" required>
                                <c:forEach var="b" items="${branches}">
                                    <option value="${b.id}" ${not empty proposal && proposal.branchId == b.id ? 'selected' : ''}>${b.name}</option>
                                </c:forEach>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Phòng ban <span class="text-danger">*</span></label>
                            <select id="departmentSelect" name="departmentId" class="form-select" onchange="filterPositions()" required>
                                <option value="">-- Chọn phòng ban --</option>
                                <c:forEach var="d" items="${departments}">
                                    <option value="${d.id}" ${not empty proposal && proposal.departmentId == d.id ? 'selected' : ''}>${d.name}</option>
                                </c:forEach>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Vị trí công việc <span class="text-danger">*</span></label>
                            <select id="positionSelect" name="positionId" class="form-select" onchange="handlePositionChange()" required>
                                <option value="">-- Chọn vị trí --</option>
                                <c:forEach var="p" items="${positions}">
                                    <option value="${p.id}" data-dept="${p.departmentId}" ${not empty proposal && proposal.positionId == p.id ? 'selected' : ''}>${p.title}</option>
                                </c:forEach>
                            </select>
                        </div>
                    </div>

                    <!-- 4. LOẠI NHÂN SỰ -->
                    <div class="row g-3 mb-4">
                        <div class="col-md-4">
                            <label class="form-label">Loại nhân sự <span class="text-danger">*</span></label>
                            <select id="employeeTypeSelect" name="employeeType" class="form-select" onchange="handleEmployeeTypeChange()" required>
                                <option value="FULL_TIME" ${not empty proposal && proposal.employmentType == 'FULL_TIME' ? 'selected' : ''}>FULL_TIME (Chính thức)</option>
                                <option value="PART_TIME" ${not empty proposal && proposal.employmentType == 'PART_TIME' ? 'selected' : ''}>PART_TIME (Bán thời gian)</option>
                                <option value="CASUAL" ${not empty proposal && proposal.employmentType == 'CASUAL' ? 'selected' : ''}>CASUAL (Thời vụ)</option>
                            </select>
                        </div>

                        <div class="col-md-4" id="shiftContainer" style="display: none;">
                            <label class="form-label">Ca đăng ký cố định <span class="text-danger">*</span></label>
                            <select id="shiftSelect" name="shiftType" class="form-select">
                                <option value="SANG" ${not empty proposal && proposal.shiftType == 'SANG' ? 'selected' : ''}>Ca Sáng (06:00 - 12:00)</option>
                                <option value="CHIEU" ${not empty proposal && proposal.shiftType == 'CHIEU' ? 'selected' : ''}>Ca Chiều (12:00 - 18:00)</option>
                                <option value="TOI" ${not empty proposal && proposal.shiftType == 'TOI' ? 'selected' : ''}>Ca Tối (18:00 - 22:00)</option>
                            </select>
                        </div>

                        <div class="col-md-4" id="expirationDateContainer" style="display: none;">
                            <label class="form-label">Ngày kết thúc hợp đồng <span class="text-danger">*</span></label>
                            <input type="date" id="expirationDateInput" name="expirationDate" value="${not empty proposal ? proposal.expirationDate : ''}" class="form-control">
                        </div>
                    </div>

                    <div class="text-end">
                        <button type="submit" class="btn btn-primary px-4">Xác Nhận Phê Duyệt & Cấp Tài Khoản</button>
                    </div>
                </form>
            </div>
        </div>

        <script>
            function filterPositions() {
                const deptId = document.getElementById('departmentSelect').value;
                const positionSelect = document.getElementById('positionSelect');
                const options = positionSelect.querySelectorAll('option');

                options.forEach(opt => {
                    if (opt.value === "")
                        return;
                    if (deptId === "" || opt.getAttribute('data-dept') === deptId) {
                        opt.style.display = "block";
                    } else {
                        opt.style.display = "none";
                    }
                });
            }

            // Tự động map Phòng ban dựa trên Vị trí được chọn
            function handlePositionChange() {
                const posSelect = document.getElementById('positionSelect');
                const selectedOption = posSelect.options[posSelect.selectedIndex];

                if (!selectedOption || selectedOption.value === "") return;

                const posText = selectedOption.text.toLowerCase();
                const deptSelect = document.getElementById('departmentSelect');

                const isSalesOrCashier = posText.includes("thu ngân") || posText.includes("bán hàng") || posText.includes("trưng bày");

                for (let i = 0; i < deptSelect.options.length; i++) {
                    const deptText = deptSelect.options[i].text.toLowerCase();
                    if (isSalesOrCashier) {
                        if (deptText.includes("thu ngân") || deptText.includes("bán hàng")) {
                            deptSelect.selectedIndex = i;
                            break;
                        }
                    } else {
                        if (deptText.includes("vận hành")) {
                            deptSelect.selectedIndex = i;
                            break;
                        }
                    }
                }

                filterPositions();
            }

            function handleEmployeeTypeChange() {
                const type = document.getElementById('employeeTypeSelect').value;
                const shiftContainer = document.getElementById('shiftContainer');
                const shiftSelect = document.getElementById('shiftSelect');
                const expContainer = document.getElementById('expirationDateContainer');
                const expInput = document.getElementById('expirationDateInput');

                if (type === 'PART_TIME') {
                    shiftContainer.style.display = 'block';
                    shiftSelect.required = true;
                    expContainer.style.display = 'none';
                    expInput.required = false;
                    expInput.value = '';
                } else if (type === 'CASUAL') {
                    shiftContainer.style.display = 'none';
                    shiftSelect.required = false;
                    expContainer.style.display = 'block';
                    expInput.required = true;
                } else {
                    shiftContainer.style.display = 'none';
                    shiftSelect.required = false;
                    expContainer.style.display = 'none';
                    expInput.required = false;
                    expInput.value = '';
                }
            }

            document.addEventListener("DOMContentLoaded", function () {
                const posSelect = document.getElementById('positionSelect');
                if (posSelect.value !== "") {
                    handlePositionChange();
                } else {
                    filterPositions();
                }
                handleEmployeeTypeChange();
            });

            document.getElementById('roleSelect').addEventListener('change', function () {
                let roleId = this.value;

                fetch('${pageContext.request.contextPath}/hr/create-user?action=getRoleConfig&roleId=' + roleId)
                        .then(response => response.json())
                        .then(data => {
                            document.getElementById('usernameInput').value = data.code;

                            const deptSelect = document.getElementById('departmentSelect');
                            const posSelect = document.getElementById('positionSelect');

                            if (data.deptId > 0) {
                                deptSelect.value = data.deptId;
                                filterPositions();
                            } else {
                                deptSelect.value = "";
                                filterPositions();
                            }

                            if (data.posId > 0) {
                                posSelect.value = data.posId;
                            } else {
                                posSelect.value = "";
                            }
                        })
                        .catch(error => console.error('Lỗi nhận dữ liệu cấu hình:', error));
            });
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>